apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: pipeline-binding-k8s-ingress
spec:
  params:
  - name: CLUSTER
    value: $(body.CLUSTER)
  - name: NAMESPACE
    value: $(body.NAMESPACE)
  - name: EXTERNALPORT
    value: $(body.EXTERNALPORT)
  - name: SERVICE
    value: $(body.SERVICE)
  - name: INTERNALPORT
    value: $(body.INTERNALPORT)
  - name: KUBECONFIG
    value: $(body.KUBECONFIG)
  - name: AUTHTYPE
    value: $(body.AUTHTYPE)
  - name: USERNAME
    value: $(body.USERNAME)
  - name: PASSWORD
    value: $(body.PASSWORD)
  - name: SERVER_CALLBACK_URL
    value: $(body.SERVER_CALLBACK_URL)
  - name: SERVER_TOKEN
    value: $(body.SERVER_TOKEN)