apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-smartide-cli

spec:
  description: >-
    This Task is Golang task to test Go projects.

  params:
    - name: COMMAND
      description: smartide command
      type: string
      default: 
    - name: HOST
      description: SSH host
      type: string
      default: 
    - name: SSH_USER_NAME
      description: ssh login user name
      type: string
      default: 
    - name: SSH_USER_PASSWORD
      description: password
      type: string
      default: ""
    - name: GIT_CLONE_URL
      description: git clone url
      type: string
      default: 

    - name: SERVER_WORK_SPACE_ID
      description: 服务端工作区ID
      type: string
      default:   
    - name: SERVER_WORK_SPACE_NO
      description: 服务端工作区NO
      type: string
      default:   
    - name: SERVER_USER_NAME
      description: 服务端用户名
      type: string
      default:   
    - name: SERVER_USER_GUID
      description: 服务端用户GUID
      type: string
      default:   
    - name: SERVER_LOGIN_URL
      description: server 登录地址
      type: string
      default: 
    - name: SERVER_FEEDBACK
      description: 服务端反馈URL
      type: string
      default:   
    - name: SERVER_TOKEN
      description: 服务端TOKEN
      type: string
      default: 

  steps:
    - name: smartide-cli
      image: registry.cn-hangzhou.aliyuncs.com/smartide/smartide-cli:2377
      script: |
        #!/bin/bash

        echo "hello smartide"

        se version      

        if [ "$(params.COMMAND)" == "start" ]; then 
           echo "smartide $(params.COMMAND) running"
           se start --debug --mode server --host '$(params.HOST)' --username '$(params.SSH_USER_NAME)' --password '$(params.SSH_USER_PASSWORD)' --repourl '$(params.GIT_CLONE_URL)' --serverworkspaceid '$(params.SERVER_WORK_SPACE_ID)' --serverusername '$(params.SERVER_USER_NAME)' --serveruserguid '$(params.SERVER_USER_GUID)' --serverfeedback '$(params.SERVER_FEEDBACK)' --servertoken '$(params.SERVER_TOKEN)'  
        else 
           echo "smartide $(params.COMMAND) $(params.SERVER_WORK_SPACE_NO) running"
           se login '$(params.SERVER_LOGIN_URL)' --username '$(params.SERVER_USER_NAME)' --password '$(params.SERVER_TOKEN)'           
           se $(params.COMMAND) $(params.SERVER_WORK_SPACE_NO) --debug --mode server --serverworkspaceid '$(params.SERVER_WORK_SPACE_ID)' --serverusername '$(params.SERVER_USER_NAME)' --serveruserguid '$(params.SERVER_USER_GUID)' --serverfeedback '$(params.SERVER_FEEDBACK)' --servertoken '$(params.SERVER_TOKEN)'
        fi

        echo "end"

        
