apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-smartide-cli

spec:
  description: >-
    This Task is Golang task to test Go projects.

  params:
    - name: HOST
      description: SSH host
      type: string
      default: 
    - name: SSH_USER_NAME
      description: ssh login user name
      type: string
      default: 
    - name: SSH_USER_PASSWORD
      description: password
      type: string
      default: ""
    - name: GIT_CLONE_URL
      description: git clone url
      type: string
      default: 

    - name: SERVER_WORK_SPACE_ID
      description: 服务端工作区ID
      type: string
      default:   
    - name: SERVER_USER_NAME
      description: 服务端用户名
      type: string
      default:   
    - name: SERVER_USER_GUID
      description: 服务端用户GUID
      type: string
      default:   
    - name: SERVER_FEEDBACK
      description: 服务端反馈URL
      type: string
      default:   
    - name: SERVER_TOKEN
      description: 服务端TOKEN
      type: string
      default: 

  steps:
    - name: smartide-cli
      image: registry.cn-hangzhou.aliyuncs.com/smartide/smartide-cli:build
      script: |
        #!/bin/bash

        echo "hello smartide"

        echo $(params.SERVER_WORK_SPACE_ID)
        echo $(params.SERVER_USER_NAME)
        echo $(params.SERVER_USER_GUID)
        echo $(params.SERVER_FEEDBACK)
        echo $(params.SERVER_TOKEN)

        se version

        se start --debug --mode server --host '$(params.HOST)'  --username '$(params.SSH_USER_NAME)'  --password '$(params.SSH_USER_PASSWORD)' --repourl '$(params.GIT_CLONE_URL)' --serverworkspaceid '$(params.SERVER_WORK_SPACE_ID)' --serverusername '$(params.SERVER_USER_NAME)' --serveruserguid '$(params.SERVER_USER_GUID)' --serverfeedback '$(params.SERVER_FEEDBACK)' --servertoken '$(params.SERVER_TOKEN)'  
                       

        echo "end"

        
