apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-triggers-smartide-cli-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: triggers-smartide-cli-eventlistener-binding
subjects:
- kind: ServiceAccount
  name: tekton-triggers-smartide-cli-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-roles
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: triggers-smartide-cli-eventlistener-clusterbinding
subjects:
- kind: ServiceAccount
  name: tekton-triggers-smartide-cli-sa
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-clusterroles