apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: pipeline-binding-smartide-cli
spec:
  params:
  - name: contenttype
    value: $(header.Content-Type)
  - name: COMMAND
    value: $(body.COMMAND)
  - name: HOST
    value: $(body.HOST)
  - name: SSH_USER_NAME
    value: $(body.SSH_USER_NAME)
  - name: SSH_USER_PASSWORD
    value: $(body.SSH_USER_PASSWORD)
  - name: GIT_CLONE_URL
    value: $(body.GIT_CLONE_URL)
  - name: GIT_BRANCH
    value: $(body.GIT_BRANCH)

  - name: SERVER_WORK_SPACE_ID
    value: $(body.SERVER_WORK_SPACE_ID)
  - name: SERVER_WORK_SPACE_NO
    value: $(body.SERVER_WORK_SPACE_NO)
  - name: SERVER_USER_NAME
    value: $(body.SERVER_USER_NAME)
  - name: SERVER_USER_GUID
    value: $(body.SERVER_USER_GUID)
  - name: SERVER_FEEDBACK
    value: $(body.SERVER_FEEDBACK)
  - name: SERVER_LOGIN_URL
    value: $(body.SERVER_LOGIN_URL)
  - name: SERVER_TOKEN
    value: $(body.SERVER_TOKEN)
