---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: trigger-listener-smartide-cli
spec:
  serviceAccountName: tekton-triggers-smartide-cli-sa
  triggers:
    - name: trigger-smartide-cli
      bindings:
        - ref: pipeline-binding-smartide-cli
      template:
        ref: pipeline-template-smartide-cli