apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: pipeline-binding-k8s-ssh
spec:
  params:
  - name: BASEDNSNAME
    value: $(body.BASEDNSNAME)
  - name: CLUSTER
    value: $(body.CLUSTER)
  - name: SSHCONFIG
    value: $(body.SSHCONFIG)
  - name: KUBECONFIG
    value: $(body.KUBECONFIG)
  - name: SERVER_CALLBACK_URL
    value: $(body.SERVER_CALLBACK_URL)
  - name: SERVER_TOKEN
    value: $(body.SERVER_TOKEN)