apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: pipeline-template-k8s-ssh
spec:
  params:
    - name: BASEDNSNAME
      description: the base dns name of smartide server
      default: "ws.smartide.cn"
    - name: CLUSTER
      description: the k8s cluster name (ws-xxx)
      default: "ws"
    - name: SSHCONFIG
      description: the ssh list config string
      default:
    - name: KUBECONFIG
      description: the k8s cluster config
      default:
    - name: SERVER_CALLBACK_URL
      description: server callback url
      default: ""
    - name: SERVER_TOKEN
      description: server token
      default: ""

  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: pipeline-k8s-ssh-run-
    spec:
      pipelineRef:
        name: pipeline-k8s-ssh
      params:
      - name: BASEDNSNAME
        value: $(tt.params.BASEDNSNAME)
      - name: CLUSTER
        value: $(tt.params.CLUSTER)
      - name: SSHCONFIG
        value: $(tt.params.SSHCONFIG)
      - name: KUBECONFIG
        value: $(tt.params.KUBECONFIG)
      - name: SERVER_CALLBACK_URL
        value: $(tt.params.SERVER_CALLBACK_URL)
      - name: SERVER_TOKEN
        value: $(tt.params.SERVER_TOKEN)